lab7/GrzegorzMaciejewskiLab7ZadanieDomowe/GrzegorzMaciejewskiLab7ZadanieDomowe/Controllers/FlightController.cs
using GrzegorzMaciejewskiLab7ZadanieDomowe.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GrzegorzMaciejewskiLab7ZadanieDomowe.Controllers
{
    public class FlightController : Controller
    {
        // GET: Flight
        public ActionResult Index()
        {
            //var entities = new GrzegorzMaciejewskiLab7ZadanieDomoweEntities();
            return View();
        }

        public JsonResult GetListOfFlights()
        {
            var ctx = new GrzegorzMaciejewskiLab7Entities();
            List<Loty> list = ctx.Loty.ToList();
            return Json(list, JsonRequestBehavior.AllowGet);
        }
        public ActionResult UpdateSeatsAmount(int id, int tickets)
        {
            Loty flight;
            using (var ctx = new GrzegorzMaciejewskiLab7Entities())
            {
                flight = ctx.Loty.FirstOrDefault(m => m.ID == id);
                flight.WolneMiejsca = tickets;
                ctx.SaveChanges();
            }
            return View("Index");
        }

        public ActionResult AddCustomerToDatabase(string name, string surname, int flightId, int tickets)
        {
            Customers customer;
            using (var ctx = new GrzegorzMaciejewskiLab7Entities())
            {
                customer = new Customers()
                {
                    Name = name,
                    Surname = surname,
                    FlightID = flightId,
                    TicketsAmount = tickets
                };
                ctx.Customers.Add(customer);
                ctx.SaveChanges();
            }
            return View("Index");
        }
    }
}

lab7/GrzegorzMaciejewskiLab7ZadanieDomowe/GrzegorzMaciejewskiLab7ZadanieDomowe/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Witaj na stronie Lotniska</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Lotnisko", "Index", "Flight", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Loty", "Index", "Flight")</li>
                </ul>
             
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year </p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>